#!/bin/bash
until tail /var/log/cloud-init.log | grep -q " Cloud-init v. ..... finished at " ; do echo "waiting for cloud-init" ; sleep 5s ; done
sudo /usr/local/bin/cluster_up.sh
until oc login localhost:8443 --username=developer --password=developer --insecure-skip-tls-verify=true | grep -q "myproject" ; do sleep 5s ; done

